### ISSUE TITLE
Weight file

### ISSUE THREAD

**Issue by wangzhangfei-hkd** [EpsAvlc/LiDAR_Super_Resolution_Pytorch#1]
Dear EpsAvlc, is it convenient for you to send a weighting document? We are ready to reproduce your algorithm. Thank you

**Comment by EpsAvlc** [comment]
Sorry that i didn't get valid results from my implement, and the loss can't be lower. Maybe something I made some mistakes. You can refer to the origin repo I cite in readme.md.

**Comment by wangzhangfei-hkd** [comment]
Thank you very much

**Comment by tdcsu** [comment]
thanks the comments you gave here to save my time !!!
